### PR TITLE
Update synology_SMART_control2.sh

### PR DESCRIPTION
**Pull request by 007revad**
- Fixed missing "; then" lines 460 and 463
- Fixed missing -e line 83
- Removed fdisk errors line 210 and 211
- Replaced > with -gt for numeric comparison lines 217 and 219
- Replace legacy backticks with $( ) line 176, 
- Double quote all "${3}/${4}"
- Double quote "${1}" line 144
- Double quote many other variables
- Changed to [[ ]] on lines where [ ] was used and variable was unquoted

### CODE REVIEW

**Comment by 007revad** [comment]
I've fixed an issue that prevented the script from running, and hid the fdisk error messages, as well as fixing issues that www.shellcheck.com complained about.

**Comment by wallacebrf** [comment]
i have addressed some of these already after our previous discussion yesterday and made some other changes to add some features like manual short tests, and saving more details to the test history logs, and saving extended test estimated time duration so the eventual web-interface can show it to the user


i will roll these other changes into the main branch tomorrow


i also had to use ```if [[ -z "$syno_check" ]]; then``` rather than the ```if [[ -n "$syno_check" ]]; then``` you suggested otherwise the logic was backwards. 

i will post the updated code with all of my latest changes plus all of the changes in this PULL request some time tomorrow

appreciate the support

**Comment by wallacebrf** [comment]
latest file as of tonight
https://github.com/wallacebrf/Synology-SMART-test-scheduler/blob/main/synology_smart/synology_SMART_control.sh

the file ending "2" was just a place so i could add notes while at work.

**Comment by 007revad** [comment]
I was creating a pull request to fix the [[ -n "$syno_check" ]] instead of [[ -z "$syno_check" ]] issue when I noticed you'd fixed it already, and made other changes.

**Pull request closed without merging**
