### PR TITLE
Update synology_SMART_control.sh

### PR DESCRIPTION
**Pull request by 007revad**
- Hide fdisk warnings on Asustor.
- Fix shellcheck complaints.

### CODE REVIEW

**Comment by 007revad** [comment]
Does not clobber your latest changes.

**Comment by 007revad** [comment]
I missed the missing -e on line 58
```
echo "Failed to acquire lock.\n" >&2
```
should be:
```
echo -e "Failed to acquire lock.\n" >&2
```

**Comment by wallacebrf** [comment]
Awesome really appreciate it

**Comment by wallacebrf** [comment]
Dave updates

**Pull request merged**
